---
language: go
services:
  - postgresql
  - mysql
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbcleaner_test'
  - mysql -u root --default-character-set=utf8 dbcleaner_test < fixtures/schema.sql
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
